redditclone/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/', views.signup, name="signup"),
    url(r'^login/', views.loginview, name="login"),
    url(r'^logout/', views.logoutview, name="logout"),

]

redditclone/posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'posts'

urlpatterns = [
    url(r'^create/', views.create, name="create"),
    url(r'^(?P<pk>[0-9]+)/upvote', views.upvote, name="upvote"),
    url(r'^(?P<pk>[0-9]+)/downvote', views.downvote, name="downvote"),
    url(r'^user/(?P<fk>[0-9]+)', views.userposts, name="userposts"),


]

redditclone/redditclone/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from posts import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^posts/', include('posts.urls')),
    url(r'^$', views.home, name="home" ),

]

redditclone/posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    url = models.TextField()
    pub_date = models.DateTimeField()
    author = models.ForeignKey(User)
    votes_total = models.IntegerField(default=1)

    def pub_date_pretty(self):
        return self.pub_date.strftime('%b %e %Y')

redditclone/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout


# Create your views here.

def signup(request):
    if request.method == 'POST':
        if request.POST['password1'] == request.POST['password2']:

            try:
                user = User.objects.get(username=request.POST['username'])
                return render(request, 'accounts/signup.html', {'error': 'Username has already been taken!'})
            except User.DoesNotExist:

                user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
                login(request, user)
                return render(request, 'accounts/signup.html')
        else:
            return render(request, 'accounts/signup.html', {'error': 'Passwords did not match!'})
    else:
        return render(request, 'accounts/signup.html')


def loginview(request):
    if request.method == 'POST':
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])

        if user is not None:
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST['next'])
            return redirect('home')
        else:
            return render(request, 'accounts/login.html', {'error': 'Login credentials unknown'})
    else:
        return render(request, 'accounts/login.html')

def logoutview(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')

redditclone/posts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.utils import timezone
from .models import Post


# Create your views here.
@login_required
def create(request):
    if request.method == 'POST':
        if request.POST['title'] and request.POST['url']:
            post = Post()
            post.title = request.POST['title']
            if request.POST['url'].startswith('http://') or request.POST['url'].startswith('https://'):
                post.url = request.POST['url']
            else:
                post.url = 'http://' + request.POST['url']
            post.pub_date = timezone.datetime.now()
            post.author = request.user
            post.save()
            return redirect('home')
        else:
            return render(request, 'posts/create.html', {'error':'Title and URL are required!'})
    else:
        return render(request, 'posts/create.html')

def home(request):
    posts = Post.objects.order_by('-votes_total')
    return render(request, 'posts/home.html', {'posts':posts})

def upvote(request, pk):
    if request.method == 'POST':
        post = Post.objects.get(pk=pk)
        post.votes_total += 1
        post.save()
        return redirect('home')

def downvote(request, pk):
    if request.method == 'POST':
        post = Post.objects.get(pk=pk)
        post.votes_total -= 1
        post.save()
        return redirect('home')

def userposts(request, fk):
    posts = Post.objects.filter(author__id=fk).order_by('-votes_total')
    author = User.objects.get(pk=fk)
    return render(request, 'posts/userposts.html', {'posts':posts, 'author':author})

redditclone/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content%}

<h1>Log In</h1>
  {% if error %}
    {{ error }}
  {% endif %}
  <br>
  <br>
  <form class="" action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}

    {% if request.GET.next %}
      <input type="hidden" name="next" value="{{request.GET.next}}">
    {% endif %}

    Username:
    <br>
    <input type="text" name="username">
    <br>
    Password:
    <br>
    <input type="password" name="password">
    <br>
    <br>
    <input class="btn" type="submit" value="Log In">
  </form>

{% endblock %}

redditclone/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content%}

<h1>Sign Up!</h1>
  {% if error %}
    {{ error }}
  {% endif %}
  <br>
  <br>
  <form class="" action="{% url 'accounts:signup' %}" method="POST">
    {% csrf_token %}
    Username:
    <br>
    <input type="text" name="username">
    <br>
    Password:
    <br>
    <input type="password" name="password1">
    <br>
    Confirm Password:
    <br>
    <input type="password" name="password2">
    <br>
    <br>
    <input class="btn" type="submit" value="Signup!">
  </form>

{% endblock %}

redditclone/posts/templates/posts/create.html
{% extends 'base.html' %}

{% block content%}

<h1>New Post</h1>
  {% if error %}
    {{ error }}
  {% endif %}
  <br>
  <br>
  <form class="" action="{% url 'posts:create' %}" method="POST">
    {% csrf_token %}


    Title:
    <br>
    <input type="text" name="title">
    <br>
    URL:
    <br>
    <input type="text" name="url">
    <br>
    <br>
    <input class="btn" type="submit" value="Post">
  </form>

{% endblock %}

redditclone/posts/templates/posts/home.html
{% extends 'base.html' %}

{% block content%}

<h1>The homepage of nowhere</h1>
<a href="{% url 'posts:create' %}" class="btn btn-primary">New Post</a>

<br>
<br>

{% for post in posts.all %}

<table>
  <tr>
    <td style="padding-right: 30px;"><a href="#" onclick="document.getElementById('upvote{{ post.id }}').submit()"><span class="glyphicon glyphicon-triangle-top" aria-hidden="true"></span></a><br> {{ post.votes_total }} <br><a href="#" onclick="document.getElementById('downvote{{ post.id }}').submit()"><span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></span></a></td>
    <td><a href="{{ post.url }}">{{ post.title }}</a><br>{{ post.pub_date_pretty }} by {{ post.author.username }}</td>
  </tr>
</table>
<br>
<br>

<br>
<br>
<form id="upvote{{ post.id }}" action="{% url 'posts:upvote' post.id %}" method="POST">
  {% csrf_token %}
  <input class="btn" type="hidden">
</form>

<form id="downvote{{ post.id }}" action="{% url 'posts:downvote' post.id %}" method="POST">
 {% csrf_token %}
 <input class="btn" type="hidden">
</form>

{% endfor %}
<br>
<br>

{% endblock %}

redditclone/posts/templates/posts/userposts.html
{% extends 'base.html' %}

{% block content%}

<h1>All posts by {{ author.username }}</h1>


{% for post in posts.all %}

<table>
  <tr>
    <td style="padding-right: 30px;"><a href="#" onclick="document.getElementById('upvote{{ post.id }}').submit()"><span class="glyphicon glyphicon-triangle-top" aria-hidden="true"></span></a><br> {{ post.votes_total }} <br><a href="#" onclick="document.getElementById('downvote{{ post.id }}').submit()"><span class="glyphicon glyphicon-triangle-bottom" aria-hidden="true"></span></a></td>
    <td><a href="{{ post.url }}">{{ post.title }}</a><br>{{ post.pub_date_pretty }} by {{ post.author.username }}</td>
  </tr>
</table>
<br>
<br>

<br>
<br>
<form id="upvote{{ post.id }}" action="{% url 'posts:upvote' post.id %}" method="POST">
  {% csrf_token %}
  <input class="btn" type="hidden">
</form>

<form id="downvote{{ post.id }}" action="{% url 'posts:downvote' post.id %}" method="POST">
 {% csrf_token %}
 <input class="btn" type="hidden">
</form>

{% endfor %}
<br>
<br>

{% endblock %}

redditclone/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Reddit Clone</title>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" ></script>
</head>
<body>
  <header>
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">Reddit Clone</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li><a href="#" onclick="document.getElementById('logout').submit()">Log Out</a></li>
        <form id="logout" action="{% url 'accounts:logout' %}" method="post">
          {% csrf_token %}
          <input type="hidden">
        </form>
        {% else %}
        <li><a href="{% url 'accounts:signup'%}">Sign Up</a></li>
        <li><a href="{% url 'accounts:login'%}">Log In</a></li>
        {% endif %}


      </ul>
    </div>
  </div>
</nav>
  </header>
  <main>
    <div class="container">
      {% block content %}
      {% endblock%}
    </div>
  </main>
</body>
</html>